networking:
  # If enabled, hcloud-ccm will be deployed with networking support.
  enabled: false
  # If networking is enabled, clusterCIDR must match the PodCIDR subnet your cluster has been configured with.
  # The default "10.244.0.0/16" assumes you're using Flannel with default configuration.
  clusterCIDR: 10.244.0.0/16
# Resource requests for the deployed hccm Pod.
resources:
  requests:
    cpu: 100m
    memory: 50Mi
