tasks:
  - init: |-
      curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" &&
      sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl && rm kubectl &&
      curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
  - init: go get && go build ./...
    command: go run .
