version: "2"

run:
  timeout: 5m

linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - copyloopvar
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - forbidigo
    - gocheckcompilerdirectives
    - gochecksumtype
    - gocritic
    - godot
    - gomoddirectives
    - gomodguard
    - gosec
    - gosmopolitan
    - govet
    - importas
    - ineffassign
    - loggercheck
    - makezero
    - misspell
    - musttag
    - nilerr
    - nilnesserr
    - noctx
    - prealloc
    - protogetter
    - reassign
    - recvcheck
    - revive
    - rowserrcheck
    - spancheck
    - staticcheck
    - testifylint
    - unparam
    - unused
    - whitespace

  settings:
    exhaustive:
      default-signifies-exhaustive: true

    staticcheck:
      checks: ["all", "-QF1008"]

    gomoddirectives:
      replace-allow-list:
        - github.com/hetznercloud/hcloud-go/v2
        - k8s.io/cloud-provider
        - k8s.io/controller-manager

    importas:
      alias:
        - pkg: k8s.io/api/core/v1
          alias: corev1
        - pkg: k8s.io/apimachinery/pkg/apis/meta/v1
          alias: metav1
        - pkg: github.com/syself/hrobot-go
          alias: hrobot
        - pkg: github.com/syself/hrobot-go/models
          alias: hrobotmodels
      no-unaliased: true

  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - std-error-handling
    rules:
      - linters:
          - testifylint
        text: require-error
      - linters:
          - godot
        path: internal/annotation/load_balancer.go
      - linters:
          - godot
        path: internal/config/load_balancer_envs.go
      - linters:
          - errcheck
          - gosec
        path: (_test\.go|testing\.go|testsupport|e2etests)
      - linters:
          - revive
          - unparam
        path: internal/mocks
      - linters:
          - revive
        path: internal/utils/.+\.go
        text: var-naming

formatters:
  enable:
    - gci
    - goimports

  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/hetznercloud)

  exclusions:
    generated: lax
