dist: xenial
language: go
go:
  - 1.12
env:
  - GO111MODULE=on
before_script:
  - go get golang.org/x/lint/golint
  - docker pull lkdevelopment/hetzner-cloud-api-mock
  - docker run -d -p 127.0.0.1:4000:8080 lkdevelopment/hetzner-cloud-api-mock
  - docker ps -a
  - sleep 10
script:
  - make test
  - make
