apiVersion: skaffold/v4beta3
kind: Config
metadata:
  name: cloud-controller-manager
build:
  artifacts:
    - image: hetznercloud/hcloud-cloud-controller-manager
      docker:
        dockerfile: hack/Dockerfile
        cacheFrom:
          - hetznercloud/hcloud-cloud-controller-manager:buildcache
  local:
    useBuildkit: true
  insecureRegistries:
    - localhost:30666
manifests:
  helm:
    releases:
      - name: hccm
        chartPath: chart
        setValues:
          networking.enabled: true
