apiVersion: skaffold/v4beta3
kind: Config
metadata:
  name: cloud-controller-manager
build:
  artifacts:
    - image: hetznercloud/hcloud-cloud-controller-manager
      runtimeType: go
      docker:
        dockerfile: hack/Dockerfile
        cacheFrom:
          - hetznercloud/hcloud-cloud-controller-manager:buildcache
  local:
    useBuildkit: true
  insecureRegistries:
    - localhost:30666
manifests:
  helm:
    releases:
      - name: hccm
        namespace: kube-system
        chartPath: chart
        setValues:
          networking.enabled: true

profiles:
  # Clusters with Robot Servers do not support the native Routing functionality right now.
  - name: robot
    patches:
      - op: replace
        path: /manifests/helm/releases/0/setValues/networking.enabled
        value: false
      - op: add
        path: /manifests/helm/releases/0/setValues/robot.enabled
        value: true
