{{- if .Values.rbac.create }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  # The prefix ":restricted" originates from removing the cluster-admin role from HCCM.
  # Renaming the ClusterRoleBinding makes the migration easier for users.
  name: "system:{{ include "hcloud-cloud-controller-manager.name" . }}:restricted"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "system:{{ include "hcloud-cloud-controller-manager.name" . }}"
subjects:
  - kind: ServiceAccount
    name: {{ include "hcloud-cloud-controller-manager.name" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
