{{ if (and $.Values.monitoring.enabled $.Values.monitoring.podMonitor.enabled) }}
{{ if $.Capabilities.APIVersions.Has "monitoring.coreos.com/v1/PodMonitor" }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "hcloud-cloud-controller-manager.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- with $.Values.monitoring.podMonitor.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- range $key, $value := .Values.monitoring.podMonitor.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  {{- tpl (toYaml $.Values.monitoring.podMonitor.spec) $ | nindent 2 }}
  selector:
    matchLabels:
      {{- include "hcloud-cloud-controller-manager.selectorLabels" . | nindent 6 }}
{{ end }}
{{ end }}
