---
name: Lint

on:
  push:
    branches: [main]
  pull_request:

jobs:
  helm:
    runs-on: ubuntu-latest
    name: Helm Validation ${{ matrix.helm }}
    strategy:
      matrix:
        helm:
          - v3.19.2 # renovate: datasource=github-releases depName=helm/helm versioning=same-major
          - v4.0.0 # renovate: datasource=github-releases depName=helm/helm versioning=same-major

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
        with:
          python-version: 3.x

      - uses: yokawasa/action-setup-kube-tools@9d39563c24d4a419d1a8289c34d6da5a6171252c # v0.13.5
        with:
          setup-tools: |
            helm
          helm: ${{ matrix.helm }}

      - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
        with:
          extra_args: none || true

      # Run with pre-commit to get diff check
      - name: helm-validation
        run: |
          pre-commit run helm-lint --all
          pre-commit run helm-snapshots --all
          pre-commit run deploy-manifests --all

  pre-commit:
    runs-on: ubuntu-latest
    env:
      # Helm lints are executed in a separate action with a version matrix
      SKIP: "helm-lint,helm-snapshots,deploy-manifests"
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
        with:
          python-version: 3.x

      - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
        with:
          path: ~/.cache/golangci-lint
          key: pre-commit-golangci-lint|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}|${{ hashFiles('**/*.go') }}
          restore-keys: |
            pre-commit-golangci-lint|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}|
            pre-commit-golangci-lint|${{ env.pythonLocation }}|
            pre-commit-golangci-lint|

      - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
