name: Robot

on:
  push:
    branches: [main]
    paths:
      - .github/workflows/robot.yml
      - dev/robot/**
  schedule:
    # At 02:30 on Monday https://crontab.guru/#30_2_*_*_1
    - cron: "30 2 * * 1"

jobs:
  install:
    runs-on: ubuntu-latest

    concurrency: robot
    environment: e2e-robot

    defaults:
      run:
        working-directory: dev/robot

    env:
      PY_COLORS: true
      ANSIBLE_FORCE_COLOR: true

    steps:
      - uses: actions/checkout@v4

      - name: Install robot server
        env:
          ROBOT_USER: ${{ secrets.ROBOT_USER }}
          ROBOT_PASSWORD: ${{ secrets.ROBOT_PASSWORD }}
          ROBOT_SSH_KEY: ${{ secrets.ROBOT_SSH_KEY }}
        run: |
          ansible-galaxy install -r requirements.yml

          ./with-ssh-agent ansible-playbook -vv install.yml
